name: Build iOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  build:
    name: Сборка iOS приложения
    runs-on: macos-latest

    steps:
    - name: Checkout кода
      uses: actions/checkout@v4

    - name: Установка утилит
      run: |
        brew install xcbeautify jq

    - name: Установка сертификата подписи
      env:
        CERTIFICATE_P12: ${{ secrets.CERTIFICATE_P12 }}
        CERT_PASSWORD: ${{ secrets.CERT_PASSWORD }}
        PROVISIONING_PROFILE: ${{ secrets.PROVISIONING_PROFILE }}
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      run: |
        security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
        security set-keychain-settings -lut 21600 build.keychain

        echo -n "$CERTIFICATE_P12" | base64 --decode -o certificate.p12
        security import certificate.p12 -k build.keychain -P "$CERT_PASSWORD" -A

        security set-key-partition-list -S apple-tool:,apple: -s -k "$KEYCHAIN_PASSWORD" build.keychain

        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        echo -n "$PROVISIONING_PROFILE" | base64 --decode -o ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision

    - name: Определение параметров проекта
      run: |
        PROJECT_FILE=$(find . -d 1 -name "*.xcodeproj" | head -n 1)
        if [ -z "$PROJECT_FILE" ]; then
          echo "Xcode project not found"
          exit 1
        fi
        PROJECT_NAME=$(basename "$PROJECT_FILE" .xcodeproj)
        echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_ENV

        SCHEME_NAME=$(xcodebuild -project "$PROJECT_FILE" -list -json | jq -r '.project.schemes[0]')
        echo "SCHEME_NAME=$SCHEME_NAME" >> $GITHUB_ENV

    - name: Сборка и архивирование приложения
      env:
        APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      run: |
        rm -rf ~/Library/Developer/Xcode/DerivedData

        xcodebuild archive \
          -project "$PROJECT_NAME.xcodeproj" \
          -scheme "$SCHEME_NAME" \
          -configuration Release \
          -archivePath "$PROJECT_NAME.xcarchive" \
          -sdk iphoneos \
          -destination 'generic/platform=iOS' \
          -derivedDataPath derived_data \
          CODE_SIGN_STYLE=Manual \
          DEVELOPMENT_TEAM="$APPLE_TEAM_ID" \
          CODE_SIGN_IDENTITY="iPhone Distribution" \
          | xcbeautify

        if [ ! -d "$PROJECT_NAME.xcarchive" ]; then
          echo "Archive not created"
          exit 1
        fi

    - name: Экспорт IPA файла
      env:
        APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      run: |
        # Создание exportOptions.plist с правильным экранированием
        echo '<?xml version="1.0" encoding="UTF-8"?>' > exportOptions.plist
        echo '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">' >> exportOptions.plist
        echo '<plist version="1.0">' >> exportOptions.plist
        echo '<dict>' >> exportOptions.plist
        echo '    <key>method</key>' >> exportOptions.plist
        echo '    <string>app-store</string>' >> exportOptions.plist
        echo '    <key>teamID</key>' >> exportOptions.plist
        echo '    <string>'"$APPLE_TEAM_ID"'</string>' >> exportOptions.plist
        echo '    <key>compileBitcode</key>' >> exportOptions.plist
        echo '    <false/>' >> exportOptions.plist
        echo '    <key>thinning</key>' >> exportOptions.plist
        echo '    <string><none></string>' >> exportOptions.plist
        echo '</dict>' >> exportOptions.plist
        echo '</plist>' >> exportOptions.plist

        xcodebuild -exportArchive \
          -archivePath "$PROJECT_NAME.xcarchive" \
          -exportPath . \
          -exportOptionsPlist exportOptions.plist \
          | xcbeautify

        if [ ! -f "$PROJECT_NAME.ipa" ]; then
          echo "IPA file not created"
          exit 1
        fi

    - name: Создание GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.version || format('v{0}', github.run_number) }}
        release_name: Release ${{ github.event.inputs.version || format('v{0}', github.run_number) }}
        draft: false
        prerelease: false

    - name: Загрузка IPA в Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ env.PROJECT_NAME }}.ipa
        asset_name: ${{ env.PROJECT_NAME }}.ipa
        asset_content_type: application/octet-stream
